apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    spec:
      containers:
      - name: weather-api
        image: docker.pkg.github.com/zorinivana/misis_ci/api-container:1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m