name: MISIS CI DEPLOY ACTION
env:
  VERSION: ${{ 1.0.0 }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: build API container      
      working-directory: MISIS_CI/MISIS.CI.API
      run: |             
        ls -l        
        docker build -t api-container .
        docker push docker.pkg.github.com/ZorinIvanA/MISIS_CI/api-container:$VERSION