name: MISIS CI DEPLOY ACTION
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        VERSION: ${{ '1.0.0' }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: build API container      
      working-directory: MISIS_CI/MISIS.CI.API
      run: |             
        ls -l        
        docker build -t docker.pkg.github.com/zorinivana/misis_ci/api-container:$VERSION .
        docker login docker.pkg.github.com -u ${{ secrets.username }} -p ${{secrets.GITHUB_TOKEN}}
        docker push docker.pkg.github.com/zorinivana/misis_ci/api-container:$VERSION
    - name: build Gateway container      
      working-directory: MISIS_CI/MISIS.CI.Gateway
      run: |             
        ls -l        
        docker build -t docker.pkg.github.com/zorinivana/misis_ci/gateway-container:$VERSION .
        docker login docker.pkg.github.com -u ${{ secrets.username }} -p ${{secrets.GITHUB_TOKEN}}
        docker push docker.pkg.github.com/zorinivana/misis_ci/gateway-container:$VERSION
    - name: build Storage container      
      working-directory: MISIS_CI/MISIS.CI.Storage
      run: |             
        ls -l        
        docker build -t docker.pkg.github.com/zorinivana/misis_ci/storage-container:$VERSION .
        docker login docker.pkg.github.com -u ${{ secrets.username }} -p ${{secrets.GITHUB_TOKEN}}
        docker push docker.pkg.github.com/zorinivana/misis_ci/storage-container:$VERSION